#!/bin/bash
set -eo pipefail

declare -x SENTRY_BROKER_TYPE
[[ -z "${SENTRY_BROKER_TYPE}" ]] && SENTRY_BROKER_TYPE="redis"

declare -x SENTRY_BROKER_HOST
[[ -z "${SENTRY_BROKER_HOST}" ]] && SENTRY_BROKER_HOST="redis"

declare -x SENTRY_BROKER_PORT
[[ -z "${SENTRY_BROKER_PORT}" ]] && SENTRY_BROKER_PORT="6379"

declare -x SENTRY_BROKER_USERNAME
[[ -z "${SENTRY_BROKER_USERNAME}" ]] && SENTRY_BROKER_USERNAME=""

declare -x SENTRY_BROKER_PASSWORD
[[ -z "${SENTRY_BROKER_PASSWORD}" ]] && SENTRY_BROKER_PASSWORD=""

declare -x SENTRY_BROKER_DB
[[ -z "${SENTRY_BROKER_DB}" ]] && SENTRY_BROKER_DB="0"

declare -x SENTRY_BROKER_VHOST
[[ -z "${SENTRY_BROKER_VHOST}" ]] && SENTRY_BROKER_VHOST=""

declare -x SENTRY_BROKER_TEST_TIMEOUT
[[ -z "${SENTRY_BROKER_TEST_TIMEOUT}" ]] && SENTRY_BROKER_TEST_TIMEOUT="60"

declare -x SENTRY_BROKER_TEST_FAIL
[[ -z "${SENTRY_BROKER_TEST_FAIL}" ]] && SENTRY_BROKER_TEST_FAIL="true"

true
