#!/bin/bash
set -eo pipefail

declare -x SENTRY_FILESTORE_BACKEND
[[ -z "${SENTRY_FILESTORE_BACKEND}" ]] && SENTRY_FILESTORE_BACKEND="filesystem"

declare -x SENTRY_FILESTORE_BUCKET_NAME
[[ -z "${SENTRY_FILESTORE_BUCKET_NAME}" ]] && SENTRY_FILESTORE_BUCKET_NAME="sentry"

declare -x SENTRY_FILESTORE_ACCESS_KEY
[[ -z "${SENTRY_FILESTORE_ACCESS_KEY}" ]] && SENTRY_FILESTORE_ACCESS_KEY=""

declare -x SENTRY_FILESTORE_SECRET_KEY
[[ -z "${SENTRY_FILESTORE_SECRET_KEY}" ]] && SENTRY_FILESTORE_SECRET_KEY=""

true
