#!/bin/bash
set -eo pipefail

if [ -f ./setup ]
then
  source ./setup
fi

echo "Executing sentry upgrade..."
su-exec sentry sentry \
  upgrade \
  --noinput

echo "Creating admin user..."
su-exec sentry create-admin \
  "${SENTRY_ADMIN_USERNAME}" \
  "${SENTRY_ADMIN_PASSWORD}" \
  "${SENTRY_ADMIN_EMAIL}" \

echo "Launching sentry server..."
su-exec sentry sentry \
  run \
  web \
  --noinput
